In [1]:
import pandas as pd
from datetime import datetime
pd.set_option('display.max_columns', None)

In [2]:
df_stops = pd.read_csv('data/stops.txt')
df_routes = pd.read_csv('data/routes.txt')
df_stoptimes = pd.read_csv('data/stop_times.txt')
df_trips = pd.read_csv('data/trips.txt')
df_shapes = pd.read_csv('data/shapes.txt')
df_dates = pd.read_csv('data/calendar_dates.txt')

In [3]:
columns_to_drop = ['stop_headsign', 'stop_code', 'route_long_name', 'route_desc', 'route_color', 'route_text_color', 'trip_short_name']

In [4]:
result = pd.merge(df_stoptimes, df_stops, how='inner',on='stop_id')
result = pd.merge(result, df_trips, how='inner',on='trip_id')
result = pd.merge(result, df_routes, how='inner',on='route_id')
result = pd.merge(result, df_dates, how='inner',on='service_id')

In [5]:
result = result.drop(columns=columns_to_drop)

In [6]:
result['arrival_time_minutes'] = result['arrival_time'].map(lambda x: int(x[3:5]))
result['arrival_time_hours'] = result['arrival_time'].map(lambda x: int(x[:2]))
result['departure_time_minutes'] = result['departure_time'].map(lambda x: int(x[3:5]))
result['departure_time_hours'] = result['departure_time'].map(lambda x: int(x[:2]))

result['arrival_time_hours'] = result['arrival_time_hours'].apply(lambda x: x-24 if x >= 24 else x )
result['departure_time_hours'] = result['departure_time_hours'].apply(lambda x: x-24 if x >= 24 else x )

result['departure_time'] = result['departure_time'].apply(lambda x: str(int(x[:2]) - 24) + x[2:] if int(x[:2]) >= 24 else x)
result['arrival_time'] = result['arrival_time'].apply(lambda x: str(int(x[:2]) - 24) + x[2:] if int(x[:2]) >= 24 else x)

result.date = result.date.astype('str')
result['month'] = result['date'].map(lambda x: x[4:6])
result['day'] = result['date'].map(lambda x: x[6:8])
result['year'] = result['date'].map(lambda x: x[0:4])
result['date2'] = result['year'] + '-' +  result['month'] + '-' + result['day']

result['departure_time'] = result['date2'] + ' ' + result['departure_time']
result['arrival_time'] = result['date2'] + ' ' + result['arrival_time']

result['arrival_time'] = result['arrival_time'].apply(lambda x: datetime.strptime(x,'%Y-%m-%d %H:%M:%S'))
result['departure_time'] = result['departure_time'].apply(lambda x: datetime.strptime(x,'%Y-%m-%d %H:%M:%S'))

In [7]:
result

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,pickup_type,drop_off_type,stop_name,stop_lat,stop_lon,route_id,service_id,trip_headsign,direction_id,shape_id,wheelchair_accessible,agency_id,route_short_name,route_type,date,exception_type,arrival_time_minutes,arrival_time_hours,departure_time_minutes,departure_time_hours,month,day,year,date2
0,401202301122334_152_401-01,2023-01-12 23:34:00,2023-01-12 23:34:00,195,0,0,1,Jaworzniaków 01,54.318041,18.568734,401,120230112,Osowa PKP,1,401_870029,1,0,N1,700,20230112,1,34,23,34,23,01,12,2023,2023-01-12
1,401202301122334_152_401-01,2023-01-12 23:35:00,2023-01-12 23:35:00,1959,1,3,3,Elfów 01,54.315644,18.569767,401,120230112,Osowa PKP,1,401_870029,1,0,N1,700,20230112,1,35,23,35,23,01,12,2023,2023-01-12
2,401202301122334_152_401-01,2023-01-12 23:36:00,2023-01-12 23:36:00,1957,2,3,3,Osiedle Świętokrzyskie 01,54.313707,18.571342,401,120230112,Osowa PKP,1,401_870029,1,0,N1,700,20230112,1,36,23,36,23,01,12,2023,2023-01-12
3,401202301122334_152_401-01,2023-01-12 23:38:00,2023-01-12 23:38:00,1790,3,3,3,Wieżycka 01,54.318050,18.587063,401,120230112,Osowa PKP,1,401_870029,1,0,N1,700,20230112,1,38,23,38,23,01,12,2023,2023-01-12
4,401202301122334_152_401-01,2023-01-12 23:39:00,2023-01-12 23:39:00,1320,4,3,3,Niepołomicka 01,54.320205,18.595057,401,120230112,Osowa PKP,1,401_870029,1,0,N1,700,20230112,1,39,23,39,23,01,12,2023,2023-01-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2051286,4202301261601_32_004-14,2023-01-26 16:42:00,2023-01-26 16:42:00,2083,25,0,0,Żwirki i Wigury 01,54.392105,18.605795,4,220230126,Strzyża PKM,1,4_884487,1,0,4,900,20230126,1,42,16,42,16,01,26,2023,2023-01-26
2051287,4202301261601_32_004-14,2023-01-26 16:43:00,2023-01-26 16:43:00,2085,26,0,0,Jana Pawła II 01,54.394637,18.601580,4,220230126,Strzyża PKM,1,4_884487,1,0,4,900,20230126,1,43,16,43,16,01,26,2023,2023-01-26
2051288,4202301261601_32_004-14,2023-01-26 16:44:00,2023-01-26 16:44:00,2087,27,0,0,Startowa 01,54.397029,18.597542,4,220230126,Strzyża PKM,1,4_884487,1,0,4,900,20230126,1,44,16,44,16,01,26,2023,2023-01-26
2051289,4202301261601_32_004-14,2023-01-26 16:45:00,2023-01-26 16:45:00,2089,28,0,0,Zaspa 01,54.399350,18.594911,4,220230126,Strzyża PKM,1,4_884487,1,0,4,900,20230126,1,45,16,45,16,01,26,2023,2023-01-26
2051290,4202301261601_32_004-14,2023-01-26 17:11:00,2023-01-26 17:11:00,14803,45,1,1,Zajezdnia WRZESZCZ T2,54.389943,18.578994,4,220230126,Strzyża PKM,1,4_884487,1,0,4,900,20230126,1,11,17,11,17,01,26,2023,2023-01-26

<h1>Functions</h1>

In [8]:
def get_all_departures_from_bus_stop(stop_id: int, arrival_time: str):
    time = datetime.strptime(arrival_time, '%H:%M')
    all_deparutres = result[(result["stop_id"]==stop_id) &
       (result['departure_time'] >= time )]
    return all_deparutres
#df.sort_values(by=['col1', 'col2'])

In [95]:
tmp = get_all_departures_from_bus_stop(313,'00:45')
trip_idser = tmp.sort_values(by=['departure_time'])['trip_id'].iloc[:6].reset_index(drop=True)

tmp.sort_values(by=['departure_time'])

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,pickup_type,drop_off_type,stop_name,stop_lat,stop_lon,route_id,service_id,trip_headsign,direction_id,shape_id,wheelchair_accessible,agency_id,route_short_name,route_type,date,exception_type,arrival_time_minutes,arrival_time_hours,departure_time_minutes,departure_time_hours,month,day,year,date2
67756,403202301120057_12_403-17,2023-01-12 00:57:00,2023-01-12 00:57:00,313,0,1,1,Wrzeszcz PKP 06,54.381766,18.603963,403,120230112,Dworzec Główny,1,403_903534,1,0,N3,700,20230112,1,57,0,57,0,01,12,2023,2023-01-12
67852,403202301122358_101_403-18,2023-01-12 01:02:00,2023-01-12 01:02:00,313,55,1,0,Wrzeszcz PKP 06,54.381766,18.603963,403,120230112,Wrzeszcz PKP,0,403_903388,1,0,N3,700,20230112,1,2,1,2,1,01,12,2023,2023-01-12
67906,403202301130157_12_403-18,2023-01-12 01:57:00,2023-01-12 01:57:00,313,0,1,1,Wrzeszcz PKP 06,54.381766,18.603963,403,120230112,Dworzec Główny,1,403_903534,1,0,N3,700,20230112,1,57,1,57,1,01,12,2023,2023-01-12
67472,403202301120058_101_403-15,2023-01-12 02:02:00,2023-01-12 02:02:00,313,55,1,0,Wrzeszcz PKP 06,54.381766,18.603963,403,120230112,Wrzeszcz PKP,0,403_903388,1,0,N3,700,20230112,1,2,2,2,2,01,12,2023,2023-01-12
67526,403202301130248_62_403-15,2023-01-12 02:48:00,2023-01-12 02:48:00,313,0,1,1,Wrzeszcz PKP 06,54.381766,18.603963,403,120230112,Dworzec Główny,1,403_903387,1,0,N3,700,20230112,1,48,2,48,2,01,12,2023,2023-01-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1155432,110202301262246_22_110-01,2023-01-26 23:05:00,2023-01-26 23:05:00,313,13,1,0,Wrzeszcz PKP 06,54.381766,18.603963,110,120230126,Wrzeszcz PKP,1,110_904379,1,0,110,700,20230126,1,5,23,5,23,01,26,2023,2023-01-26
1098682,162202301262248_22_162-54,2023-01-26 23:15:00,2023-01-26 23:15:00,313,19,1,0,Wrzeszcz PKP 06,54.381766,18.603963,162,120230126,Wrzeszcz PKP,1,162_904257,1,0,162,700,20230126,1,15,23,15,23,01,26,2023,2023-01-26
1157831,157202301262310_32_157-51,2023-01-26 23:31:00,2023-01-26 23:31:00,313,17,1,0,Wrzeszcz PKP 06,54.381766,18.603963,157,120230126,Wrzeszcz PKP,1,157_904481,1,0,157,700,20230126,1,31,23,31,23,01,26,2023,2023-01-26
1145514,403202301262348_62_403-16,2023-01-26 23:48:00,2023-01-26 23:48:00,313,0,1,1,Wrzeszcz PKP 06,54.381766,18.603963,403,120230126,Dworzec Główny,1,403_904175,1,0,N3,700,20230126,1,48,23,48,23,01,26,2023,2023-01-26
1145931,403202301262300_71_403-17,2023-01-26 23:53:00,2023-01-26 23:53:00,313,44,1,0,Wrzeszcz PKP 06,54.381766,18.603963,403,120230126,Wrzeszcz PKP,0,403_904329,1,0,N3,700,20230126,1,53,23,53,23,01,26,2023,2023-01-26

In [81]:
trip_idser[0]

'403202301120057_12_403-17'

In [94]:
result[(result['trip_id'] == trip_idser[]) & (result['direction_id'] == 1)].sort_values(by=['stop_sequence'])

Empty DataFrame
Columns: [trip_id, arrival_time, departure_time, stop_id, stop_sequence, pickup_type, drop_off_type, stop_name, stop_lat, stop_lon, route_id, service_id, trip_headsign, direction_id, shape_id, wheelchair_accessible, agency_id, route_short_name, route_type, date, exception_type, arrival_time_minutes, arrival_time_hours, departure_time_minutes, departure_time_hours, month, day, year, date2]
Index: []

In [99]:
def trip_stops(trip_id):
    x = pd.DataFrame(result[result['trip_id'] == trip_id].sort_values(by=['stop_sequence']))
    stops = pd.concat([x['stop_id'],x['stop_name'],x['stop_lat'],x['stop_lon'],x['departure_time'],x['arrival_time']],axis = 1)
    return stops
trip_stops(trip_idser[1])

,stop_id,stop_name,stop_lat,stop_lon,departure_time,arrival_time
67833,1016,Dworzec Główny 07,54.355063,18.645812,2023-01-12 23:58:00,2023-01-12 23:58:00
67835,1013,Dworzec Główny 18,54.354833,18.645117,2023-01-12 00:00:00,2023-01-12 00:00:00
67834,1025,Hucisko 04,54.351986,18.644757,2023-01-12 00:02:00,2023-01-12 00:02:00
67872,1261,Bema 01,54.350729,18.632009,2023-01-12 00:04:00,2023-01-12 00:04:00
67873,1263,Zakopiańska 03,54.348996,18.617043,2023-01-12 00:06:00,2023-01-12 00:06:00
67874,1265,Siedlce 06,54.348584,18.606695,2023-01-12 00:07:00,2023-01-12 00:07:00
67875,1635,Emaus 02,54.347153,18.602085,2023-01-12 00:08:00,2023-01-12 00:08:00
67876,1267,Zielony Stok 02,54.346060,18.598194,2023-01-12 00:09:00,2023-01-12 00:09:00
67877,1269,Pagórkowa 02,54.345010,18.590638,2023-01-12 00:10:00,2023-01-12 00:10:00
67878,1271,Myśliwska 02,54.343804,18.581107,2023-01-12 00:12:00,2023-01-12 00:12:00
67879,1273,Lipowa 02,54.339972,18.576532,2023-01-12 00:13:00,2023-01-12 00:13:00
67880,14824,Zabornia 06,54.337798,18.570814,2023-01-12 00:14:00,2023-01-12 00:14:00
67881,1275,Damroki 02,54.338986,18.563744,2023-01-12 00:15:00,2023-01-12 00:15:00
67870,1295,Pólnicy 02,54.340495,18.559223,2023-01-12 00:15:00,2023-01-12 00:15:00
67871,1277,Źródlana 02,54.341982,18.553627,2023-01-12 00:16:00,2023-01-12 00:16:00
67882,1279,Jasień Działki 02,54.344625,18.541237,2023-01-12 00:17:00,2023-01-12 00:17:00
67883,1719,Życzliwa 02,54.345876,18.533391,2023-01-12 00:18:00,2023-01-12 00:18:00
67884,1281,Węzeł Karczemki 02,54.347322,18.528503,2023-01-12 00:19:00,2023-01-12 00:19:00
67885,1930,Szczęśliwa 02,54.349065,18.527998,2023-01-12 00:20:00,2023-01-12 00:20:00
67866,1795,Karczemki 03,54.349341,18.510376,2023-01-12 00:23:00,2023-01-12 00:23:00
67867,1721,Gostyńska Szpital 02,54.347396,18.510648,2023-01-12 00:23:00,2023-01-12 00:23:00
67868,1305,Otomińska 02,54.343526,18.510005,2023-01-12 00:24:00,2023-01-12 00:24:00
67869,1307,Kiełpino - Szkoła 02,54.339579,18.507843,2023-01-12 00:25:00,2023-01-12 00:25:00
67886,1797,Łapińska 02,54.339761,18.500985,2023-01-12 00:26:00,2023-01-12 00:26:00
67887,178,Kiełpino Górne 01,54.341982,18.498835,2023-01-12 00:27:00,2023-01-12 00:27:00
67888,1798,Łapińska 01,54.339419,18.502252,2023-01-12 00:28:00,2023-01-12 00:28:00
67856,1304,Kiełpino - Szkoła 01,54.339765,18.508109,2023-01-12 00:29:00,2023-01-12 00:29:00
67857,1302,Otomińska 01,54.344114,18.510615,2023-01-12 00:30:00,2023-01-12 00:30:00
67858,1722,Gostyńska Szpital 01,54.347921,18.510847,2023-01-12 00:31:00,2023-01-12 00:31:00
67859,1283,Karczemki 02,54.350384,18.509498,2023-01-12 00:32:00,2023-01-12 00:32:00
67860,1285,Inżynierska 02,54.352268,18.500626,2023-01-12 00:33:00,2023-01-12 00:33:00
67861,14698,Fabryczna 02,54.353566,18.493852,2023-01-12 00:34:00,2023-01-12 00:34:00
67862,1287,Kokoszki 02,54.355139,18.490386,2023-01-12 00:35:00,2023-01-12 00:35:00
67863,1289,Transportowców 02,54.358087,18.491222,2023-01-12 00:36:00,2023-01-12 00:36:00
67853,1414,Nowatorów 01,54.365273,18.493524,2023-01-12 00:37:00,2023-01-12 00:37:00
67854,1844,Sąsiedzka 01,54.369421,18.503249,2023-01-12 00:38:00,2023-01-12 00:38:00
67855,14554,Matarnia PKM 01,54.374404,18.507289,2023-01-12 00:39:00,2023-01-12 00:39:00
67836,1399,Agrarna 02,54.376793,18.507575,2023-01-12 00:40:00,2023-01-12 00:40:00
67837,1401,Astronautów 02,54.377256,18.503913,2023-01-12 00:41:00,2023-01-12 00:41:00
67838,1403,Szybowcowa 02,54.379022,18.488928,2023-01-12 00:42:00,2023-01-12 00:42:00
67864,1733,Firoga 02,54.380971,18.482341,2023-01-12 00:43:00,2023-01-12 00:43:00
67865,1731,Terminal - Cargo 02,54.382669,18.475845,2023-01-12 00:44:00,2023-01-12 00:44:00
67839,102,Port Lotniczy 02,54.382732,18.467678,2023-01-12 00:46:00,2023-01-12 00:46:00
67840,1732,Terminal - Cargo 01,54.382376,18.476017,2023-01-12 00:47:00,2023-01-12 00:47:00
67841,1404,Firoga 01,54.379766,18.483215,2023-01-12 00:48:00,2023-01-12 00:48:00
67842,1402,Szybowcowa 01,54.378814,18.488433,2023-01-12 00:49:00,2023-01-12 00:49:00
67843,1400,Astronautów 01,54.377084,18.502953,2023-01-12 00:50:00,2023-01-12 00:50:00
67844,1398,Agrarna 01,54.376279,18.509700,2023-01-12 00:51:00,2023-01-12 00:51:00
67845,1396,Harfowa 01,54.376044,18.523174,2023-01-12 00:52:00,2023-01-12 00:52:00
67846,1394,Słowackiego Działki 01,54.370579,18.556268,2023-01-12 00:55:00,2023-01-12 00:55:00
67847,1390,Potokowa 01,54.374644,18.568792,2023-01-12 00:57:00,2023-01-12 00:57:00
67848,1926,Trawki 01,54.377502,18.574583,2023-01-12 00:58:00,2023-01-12 00:58:00
67849,1924,Cmentarz Srebrzysko 01,54.377970,18.580885,2023-01-12 00:59:00,2023-01-12 00:59:00
67850,1922,Zabytkowa 01,54.379780,18.590003,2023-01-12 01:00:00,2023-01-12 01:00:00
67851,1382,Galeria Bałtycka 05,54.382986,18.598887,2023-01-12 01:01:00,2023-01-12 01:01:00
67852,313,Wrzeszcz PKP 06,54.381766,18.603963,2023-01-12 01:02:00,2023-01-12 01:02:00

#