In [1]:
import pandas as pd
from datetime import datetime
pd.set_option('display.max_columns', None)

In [2]:
df_stops = pd.read_csv('data/stops.txt')
df_routes = pd.read_csv('data/routes.txt')
df_stoptimes = pd.read_csv('data/stop_times.txt')
df_trips = pd.read_csv('data/trips.txt')
df_shapes = pd.read_csv('data/shapes.txt')
df_dates = pd.read_csv('data/calendar_dates.txt')

In [3]:
columns_to_drop = ['stop_headsign', 'stop_code', 'route_long_name', 'route_desc', 'route_color', 'route_text_color', 'trip_short_name']

In [4]:
result = pd.merge(df_stoptimes, df_stops, how='inner',on='stop_id')
result = pd.merge(result, df_trips, how='inner',on='trip_id')
result = pd.merge(result, df_routes, how='inner',on='route_id')
result = pd.merge(result, df_dates, how='inner',on='service_id')

In [5]:
result = result.drop(columns=columns_to_drop)

In [6]:
result['arrival_time_minutes'] = result['arrival_time'].map(lambda x: int(x[3:5]))
result['arrival_time_hours'] = result['arrival_time'].map(lambda x: int(x[:2]))
result['departure_time_minutes'] = result['departure_time'].map(lambda x: int(x[3:5]))
result['departure_time_hours'] = result['departure_time'].map(lambda x: int(x[:2]))

result['arrival_time_hours'] = result['arrival_time_hours'].apply(lambda x: x-24 if x >= 24 else x )
result['departure_time_hours'] = result['departure_time_hours'].apply(lambda x: x-24 if x >= 24 else x )

result['departure_time'] = result['departure_time'].apply(lambda x: str(int(x[:2]) - 24) + x[2:] if int(x[:2]) >= 24 else x)
result['arrival_time'] = result['arrival_time'].apply(lambda x: str(int(x[:2]) - 24) + x[2:] if int(x[:2]) >= 24 else x)

result.date = result.date.astype('str')
result['month'] = result['date'].map(lambda x: x[4:6])
result['day'] = result['date'].map(lambda x: x[6:8])
result['year'] = result['date'].map(lambda x: x[0:4])
result['date2'] = result['year'] + '-' +  result['month'] + '-' + result['day']

result['departure_time'] = result['date2'] + ' ' + result['departure_time']
result['arrival_time'] = result['date2'] + ' ' + result['arrival_time']

result['arrival_time'] = result['arrival_time'].apply(lambda x: datetime.strptime(x,'%Y-%m-%d %H:%M:%S'))
result['departure_time'] = result['departure_time'].apply(lambda x: datetime.strptime(x,'%Y-%m-%d %H:%M:%S'))

In [7]:
result

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,pickup_type,drop_off_type,stop_name,stop_lat,stop_lon,route_id,service_id,trip_headsign,direction_id,shape_id,wheelchair_accessible,agency_id,route_short_name,route_type,date,exception_type,arrival_time_minutes,arrival_time_hours,departure_time_minutes,departure_time_hours,month,day,year,date2
0,401202301122334_152_401-01,2023-01-12 23:34:00,2023-01-12 23:34:00,195,0,0,1,Jaworzniaków 01,54.318041,18.568734,401,120230112,Osowa PKP,1,401_870029,1,0,N1,700,20230112,1,34,23,34,23,01,12,2023,2023-01-12
1,401202301122334_152_401-01,2023-01-12 23:35:00,2023-01-12 23:35:00,1959,1,3,3,Elfów 01,54.315644,18.569767,401,120230112,Osowa PKP,1,401_870029,1,0,N1,700,20230112,1,35,23,35,23,01,12,2023,2023-01-12
2,401202301122334_152_401-01,2023-01-12 23:36:00,2023-01-12 23:36:00,1957,2,3,3,Osiedle Świętokrzyskie 01,54.313707,18.571342,401,120230112,Osowa PKP,1,401_870029,1,0,N1,700,20230112,1,36,23,36,23,01,12,2023,2023-01-12
3,401202301122334_152_401-01,2023-01-12 23:38:00,2023-01-12 23:38:00,1790,3,3,3,Wieżycka 01,54.318050,18.587063,401,120230112,Osowa PKP,1,401_870029,1,0,N1,700,20230112,1,38,23,38,23,01,12,2023,2023-01-12
4,401202301122334_152_401-01,2023-01-12 23:39:00,2023-01-12 23:39:00,1320,4,3,3,Niepołomicka 01,54.320205,18.595057,401,120230112,Osowa PKP,1,401_870029,1,0,N1,700,20230112,1,39,23,39,23,01,12,2023,2023-01-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2051286,4202301261601_32_004-14,2023-01-26 16:42:00,2023-01-26 16:42:00,2083,25,0,0,Żwirki i Wigury 01,54.392105,18.605795,4,220230126,Strzyża PKM,1,4_884487,1,0,4,900,20230126,1,42,16,42,16,01,26,2023,2023-01-26
2051287,4202301261601_32_004-14,2023-01-26 16:43:00,2023-01-26 16:43:00,2085,26,0,0,Jana Pawła II 01,54.394637,18.601580,4,220230126,Strzyża PKM,1,4_884487,1,0,4,900,20230126,1,43,16,43,16,01,26,2023,2023-01-26
2051288,4202301261601_32_004-14,2023-01-26 16:44:00,2023-01-26 16:44:00,2087,27,0,0,Startowa 01,54.397029,18.597542,4,220230126,Strzyża PKM,1,4_884487,1,0,4,900,20230126,1,44,16,44,16,01,26,2023,2023-01-26
2051289,4202301261601_32_004-14,2023-01-26 16:45:00,2023-01-26 16:45:00,2089,28,0,0,Zaspa 01,54.399350,18.594911,4,220230126,Strzyża PKM,1,4_884487,1,0,4,900,20230126,1,45,16,45,16,01,26,2023,2023-01-26
2051290,4202301261601_32_004-14,2023-01-26 17:11:00,2023-01-26 17:11:00,14803,45,1,1,Zajezdnia WRZESZCZ T2,54.389943,18.578994,4,220230126,Strzyża PKM,1,4_884487,1,0,4,900,20230126,1,11,17,11,17,01,26,2023,2023-01-26

<h1>Functions</h1>

In [8]:
def get_all_departures_from_bus_stop(stop_id: int, arrival_time: str):
    time = datetime.strptime(arrival_time, '%H:%M')
    all_deparutres = result[(result["stop_id"]==stop_id) &
       (result['departure_time'] >= time )]
    return all_deparutres
#df.sort_values(by=['col1', 'col2'])

In [95]:
tmp = get_all_departures_from_bus_stop(313,'00:45')
trip_idser = tmp.sort_values(by=['departure_time'])['trip_id'].iloc[:6].reset_index(drop=True)

tmp.sort_values(by=['departure_time'])

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,pickup_type,drop_off_type,stop_name,stop_lat,stop_lon,route_id,service_id,trip_headsign,direction_id,shape_id,wheelchair_accessible,agency_id,route_short_name,route_type,date,exception_type,arrival_time_minutes,arrival_time_hours,departure_time_minutes,departure_time_hours,month,day,year,date2
67756,403202301120057_12_403-17,2023-01-12 00:57:00,2023-01-12 00:57:00,313,0,1,1,Wrzeszcz PKP 06,54.381766,18.603963,403,120230112,Dworzec Główny,1,403_903534,1,0,N3,700,20230112,1,57,0,57,0,01,12,2023,2023-01-12
67852,403202301122358_101_403-18,2023-01-12 01:02:00,2023-01-12 01:02:00,313,55,1,0,Wrzeszcz PKP 06,54.381766,18.603963,403,120230112,Wrzeszcz PKP,0,403_903388,1,0,N3,700,20230112,1,2,1,2,1,01,12,2023,2023-01-12
67906,403202301130157_12_403-18,2023-01-12 01:57:00,2023-01-12 01:57:00,313,0,1,1,Wrzeszcz PKP 06,54.381766,18.603963,403,120230112,Dworzec Główny,1,403_903534,1,0,N3,700,20230112,1,57,1,57,1,01,12,2023,2023-01-12
67472,403202301120058_101_403-15,2023-01-12 02:02:00,2023-01-12 02:02:00,313,55,1,0,Wrzeszcz PKP 06,54.381766,18.603963,403,120230112,Wrzeszcz PKP,0,403_903388,1,0,N3,700,20230112,1,2,2,2,2,01,12,2023,2023-01-12
67526,403202301130248_62_403-15,2023-01-12 02:48:00,2023-01-12 02:48:00,313,0,1,1,Wrzeszcz PKP 06,54.381766,18.603963,403,120230112,Dworzec Główny,1,403_903387,1,0,N3,700,20230112,1,48,2,48,2,01,12,2023,2023-01-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1155432,110202301262246_22_110-01,2023-01-26 23:05:00,2023-01-26 23:05:00,313,13,1,0,Wrzeszcz PKP 06,54.381766,18.603963,110,120230126,Wrzeszcz PKP,1,110_904379,1,0,110,700,20230126,1,5,23,5,23,01,26,2023,2023-01-26
1098682,162202301262248_22_162-54,2023-01-26 23:15:00,2023-01-26 23:15:00,313,19,1,0,Wrzeszcz PKP 06,54.381766,18.603963,162,120230126,Wrzeszcz PKP,1,162_904257,1,0,162,700,20230126,1,15,23,15,23,01,26,2023,2023-01-26
1157831,157202301262310_32_157-51,2023-01-26 23:31:00,2023-01-26 23:31:00,313,17,1,0,Wrzeszcz PKP 06,54.381766,18.603963,157,120230126,Wrzeszcz PKP,1,157_904481,1,0,157,700,20230126,1,31,23,31,23,01,26,2023,2023-01-26
1145514,403202301262348_62_403-16,2023-01-26 23:48:00,2023-01-26 23:48:00,313,0,1,1,Wrzeszcz PKP 06,54.381766,18.603963,403,120230126,Dworzec Główny,1,403_904175,1,0,N3,700,20230126,1,48,23,48,23,01,26,2023,2023-01-26
1145931,403202301262300_71_403-17,2023-01-26 23:53:00,2023-01-26 23:53:00,313,44,1,0,Wrzeszcz PKP 06,54.381766,18.603963,403,120230126,Wrzeszcz PKP,0,403_904329,1,0,N3,700,20230126,1,53,23,53,23,01,26,2023,2023-01-26

In [100]:
trip_idser[0]

'403202301120057_12_403-17'

In [94]:
result[(result['trip_id'] == trip_idser[]) & (result['direction_id'] == 1)].sort_values(by=['stop_sequence'])

Empty DataFrame
Columns: [trip_id, arrival_time, departure_time, stop_id, stop_sequence, pickup_type, drop_off_type, stop_name, stop_lat, stop_lon, route_id, service_id, trip_headsign, direction_id, shape_id, wheelchair_accessible, agency_id, route_short_name, route_type, date, exception_type, arrival_time_minutes, arrival_time_hours, departure_time_minutes, departure_time_hours, month, day, year, date2]
Index: []

In [152]:
def trip_stops(trip_id):
    x = pd.DataFrame(result[result['trip_id'] == trip_id].sort_values(by=['stop_sequence']))
    stops = pd.concat([x['route_id'],x['stop_id'],x['stop_name'],x['stop_lat'],x['stop_lon'],x['departure_time'],x['arrival_time']],axis = 1)
    return stops
a = pd.DataFrame() 
for i in range(0,len(trip_idser)):
    a = pd.concat([a,trip_stops(trip_idser[i])])
a[100:]
    #for i in range(1,len(stops)):
#    trip_stops(trip_idser[I])

,route_id,stop_id,stop_name,stop_lat,stop_lon,departure_time,arrival_time
67849,403,1924,Cmentarz Srebrzysko 01,54.377970,18.580885,2023-01-12 00:59:00,2023-01-12 00:59:00
67850,403,1922,Zabytkowa 01,54.379780,18.590003,2023-01-12 01:00:00,2023-01-12 01:00:00
67851,403,1382,Galeria Bałtycka 05,54.382986,18.598887,2023-01-12 01:01:00,2023-01-12 01:01:00
67852,403,313,Wrzeszcz PKP 06,54.381766,18.603963,2023-01-12 01:02:00,2023-01-12 01:02:00
67906,403,313,Wrzeszcz PKP 06,54.381766,18.603963,2023-01-12 01:57:00,2023-01-12 01:57:00
...,...,...,...,...,...,...,...
67640,403,1926,Trawki 01,54.377502,18.574583,2023-01-12 02:58:00,2023-01-12 02:58:00
67641,403,1924,Cmentarz Srebrzysko 01,54.377970,18.580885,2023-01-12 02:59:00,2023-01-12 02:59:00
67642,403,1922,Zabytkowa 01,54.379780,18.590003,2023-01-12 03:00:00,2023-01-12 03:00:00
67643,403,1382,Galeria Bałtycka 05,54.382986,18.598887,2023-01-12 03:01:00,2023-01-12 03:01:00
67644,403,313,Wrzeszcz PKP 06,54.381766,18.603963,2023-01-12 03:02:00,2023-01-12 03:02:00

In [143]:
dfs = [items.stack for key, items in d.items()]

In [ ]:
dfs = [df.stack() for df in [d['df0'], d['df'], df3, df4]]

In [147]:
dfs[0]

<bound method DataFrame.stack of        stop_id               stop_name   stop_lat   stop_lon  \
67756      313         Wrzeszcz PKP 06  54.381766  18.603963
67757      114         Wrzeszcz PKP 03  54.381310  18.604544
67742     1383     Galeria Bałtycka 06  54.382182  18.596854
67743     1923            Zabytkowa 02  54.379187  18.587759
67744     1925  Cmentarz Srebrzysko 02  54.378149  18.579026
67745     1389               Trawki 02  54.377418  18.572632
67746     1391             Potokowa 02  54.373726  18.566521
67747     1395  Słowackiego Działki 02  54.370964  18.555768
67748     1397              Harfowa 02  54.376548  18.524945
67749     1399              Agrarna 02  54.376793  18.507575
67750     1401          Astronautów 02  54.377256  18.503913
67751     1403           Szybowcowa 02  54.379022  18.488928
67763     1733               Firoga 02  54.380971  18.482341
67764     1731     Terminal - Cargo 02  54.382669  18.475845
67786      101        Port Lotniczy 01  54.382632  18.467623
67752     1732     Terminal - Cargo 01  54.382376  18.476017
67753     1404               Firoga 01  54.379766  18.483215
67754     1402           Szybowcowa 01  54.378814  18.488433
67755     1400          Astronautów 01  54.377084  18.502953
67758     1411              Agrarna 03  54.376028  18.507976
67759    14553         Matarnia PKM 02  54.373243  18.505881
67760     1845            Sąsiedzka 02  54.370429  18.503742
67761     1290            Nowatorów 03  54.364049  18.491736
67762     1288       Transportowców 01  54.359412  18.491387
67765     1703             Kokoszki 01  54.353978  18.490334
67766     1286            Fabryczna 01  54.353067  18.494929
67767     1284          Inżynierska 01  54.351554  18.502178
67771     1282            Karczemki 01  54.349635  18.512436
67772     1929            Przytulna 01  54.348383  18.533318
67773     1931           Szczęśliwa 01  54.349134  18.528287
67774     1280      Węzeł Karczemki 01  54.347310  18.527919
67775     1720             Życzliwa 01  54.345142  18.536174
67776     1278       Jasień Działki 01  54.344322  18.542270
67777    14917             Źródlana 03  54.341635  18.550693
67768    14528             Źródlana 01  54.341903  18.553293
67769     1276        Zwierzyniecka 01  54.341550  18.555837
67778     1670              Pólnicy 01  54.339563  18.561140
67779     1274              Damroki 01  54.338673  18.564239
67780    14823             Zabornia 05  54.338123  18.573518
67781     1272               Lipowa 01  54.339456  18.576363
67782     1270            Myśliwska 01  54.344145  18.581965
67783     1268            Pagórkowa 01  54.345054  18.591451
67784     1266         Zielony Stok 01  54.345586  18.596067
67770     1264                Emaus 01  54.347458  18.604298
67785     1262         Zakopiańska 02.  54.348847  18.619052
67741     1260        Urząd Miejski 02  54.351356  18.639237
67740     1026              Hucisko 03  54.351713  18.644126
67739     1016       Dworzec Główny 07  54.355063  18.645812

           departure_time        arrival_time
67756 2023-01-12 00:57:00 2023-01-12 00:57:00
67757 2023-01-12 00:57:00 2023-01-12 00:57:00
67742 2023-01-12 00:59:00 2023-01-12 00:59:00
67743 2023-01-12 01:00:00 2023-01-12 01:00:00
67744 2023-01-12 01:01:00 2023-01-12 01:01:00
67745 2023-01-12 01:02:00 2023-01-12 01:02:00
67746 2023-01-12 01:04:00 2023-01-12 01:04:00
67747 2023-01-12 01:05:00 2023-01-12 01:05:00
67748 2023-01-12 01:08:00 2023-01-12 01:08:00
67749 2023-01-12 01:10:00 2023-01-12 01:10:00
67750 2023-01-12 01:11:00 2023-01-12 01:11:00
67751 2023-01-12 01:12:00 2023-01-12 01:12:00
67763 2023-01-12 01:13:00 2023-01-12 01:13:00
67764 2023-01-12 01:14:00 2023-01-12 01:14:00
67786 2023-01-12 01:16:00 2023-01-12 01:16:00
67752 2023-01-12 01:17:00 2023-01-12 01:17:00
67753 2023-01-12 01:18:00 2023-01-12 01:18:00
67754 2023-01-12 01:19:00 2023-01-12 01:19:00
67755 2023-01-12 01:20:00 2023-01-12 01:20:00
67758 2023-01-12 01:21:00 2023-01-12 01:21:00
67759 2023-01-12 01:21:00 2023-01-12 01:21:00
67760 2023-01-12 01:22:00 2023-01-12 01:22:00
67761 2023-01-12 01:24:00 2023-01-12 01:24:00
67762 2023-01-12 01:25:00 2023-01-12 01:25:00
67765 2023-01-12 01:26:00 2023-01-12 01:26:00
67766 2023-01-12 01:27:00 2023-01-12 01:27:00
67767 2023-01-12 01:28:00 2023-01-12 01:28:00
67771 2023-01-12 01:29:00 2023-01-12 01:29:00
67772 2023-01-12 01:32:00 2023-01-12 01:32:00
67773 2023-01-12 01:33:00 2023-01-12 01:33:00
67774 2023-01-12 01:34:00 2023-01-12 01:34:00
67775 2023-01-12 01:35:00 2023-01-12 01:35:00
67776 2023-01-12 01:36:00 2023-01-12 01:36:00
67777 2023-01-12 01:38:00 2023-01-12 01:38:00
67768 2023-01-12 01:39:00 2023-01-12 01:39:00
67769 2023-01-12 01:39:00 2023-01-12 01:39:00
67778 2023-01-12 01:40:00 2023-01-12 01:40:00
67779 2023-01-12 01:40:00 2023-01-12 01:40:00
67780 2023-01-12 01:41:00 2023-01-12 01:41:00
67781 2023-01-12 01:42:00 2023-01-12 01:42:00
67782 2023-01-12 01:43:00 2023-01-12 01:43:00
67783 2023-01-12 01:44:00 2023-01-12 01:44:00
67784 2023-01-12 01:45:00 2023-01-12 01:45:00
67770 2023-01-12 01:46:00 2023-01-12 01:46:00
67785 2023-01-12 01:48:00 2023-01-12 01:48:00
67741 2023-01-12 01:50:00 2023-01-12 01:50:00
67740 2023-01-12 01:51:00 2023-01-12 01:51:00
67739 2023-01-12 01:53:00 2023-01-12 01:53:00  >